[package]
name = "rust-sqlx"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
pretty_env_logger = "0.5.0"
sqlx = { version = "0.8.2", features = ["runtime-tokio-rustls", "postgres"] }
tokio = { version = "1.41.0", features = ["full"] }
