[package]
name = "surrealdb_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
surrealdb = "2.0.4"
tokio = { version = "1.41.0", features = ["full"] }
